# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 14:10
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('desc', models.CharField(default='anonymous', editable=False, max_length=128, verbose_name='描述')),
                ('Content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='文章内容')),
                ('create_date', models.DateTimeField(verbose_name='创建时间')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_original', models.BooleanField(default=False, verbose_name='是否原创')),
                ('is_publish', models.BooleanField(default=True, verbose_name='是否推荐')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
